### ISSUE TITLE
decrypting with node-rsa

### ISSUE THREAD

**Issue by aprilmintacpineda** [amitaymolko/react-native-rsa-native#96]
I have a form that I'm encrypting with `react-native-rsa-native`:

```js
const form = {
  value: 1,
  value2: 2
};

const encryptedBody = await RSA.encrypt(JSON.stringify(body), FORM_PUBLIC_KEY);
const body = { encryptedBody };

await fetch('/to/path', {
  body: JSON.stringify(body)
});
```

I receive it on the backend as expected, now I try to decrypt it with node-rsa:

```js
const fs = require('fs').promises;
const path = require('path');
const NodeRSA = require('node-rsa');

async function decryptFormBody (body) {
  const privateKey = await fs.readFile(
    path.join(__dirname, '../resources/forms.key'),
    'utf8'
  );

  console.log(privateKey);

  const nodeRsa = new NodeRSA(privateKey);
  const { encryptedBody } = JSON.parse(body);

  return nodeRsa.decrypt(encryptedBody);
}
```

I keep on getting this error:

```
{
    "errorType": "Error",
    "errorMessage": "Error during decryption (probably incorrect key). Original error: Error: error:04099079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error",
    "stack": [
        "Error: Error during decryption (probably incorrect key). Original error: Error: error:04099079:rsa routines:RSA_padding_check_PKCS1_OAEP_mgf1:oaep decoding error",
        "    at NodeRSA.module.exports.NodeRSA.$$decryptKey (/opt/nodejs/node_modules/node-rsa/src/NodeRSA.js:301:19)",
        "    at NodeRSA.module.exports.NodeRSA.decrypt (/opt/nodejs/node_modules/node-rsa/src/NodeRSA.js:249:21)",
        "    at decryptFormBody (/opt/nodejs/utils/decryptFormBody.js:16:18)",
        "    at async Runtime.handler (/var/task/src/functions/subscribe.js:15:25)"
    ]
}
```

I know that the private key and public keys are correct.

**Comment by aalhitennf** [comment]
I'm having similar problem, i can decrypt data from my backend but anything encrypted with RSA.encrypt cannot be decrypted but with RSA.decrypt. I also tested with multiple online decrypt sites and all of them gives various errors too.

**Comment by aalhitennf** [comment]
Fixed it. I needed to base64 decode the encrypted data at my backend.

**Comment by brbnk** [comment]
I'm having the same issue. I can't decrypt the message coming from the react native app using node-rsa. I tried to decode to base64 as @aalhitennf mentioned, but I was not well succeed

**Comment by acollazomayer** [comment]
@brbnk @aalhitennf can you share the backend code. I have the same issue

**Comment by aalhitennf** [comment]
frontend:  

```
// Generated random 16 char string
const genIv = () => {
  let result = '';
  const characters =
    'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  for (let i = 0; i < 16; i++) {
    result += characters.charAt(Math.floor(Math.random() * characters.length));
  }
  return result;
};

// Turn string into hex value
const toHex = (str: string) => {
  let result = '';
  for (let i = 0; i < str.length; i++) {
    result += str.charCodeAt(i).toString(16);
  }
  return result;
};

// Encrypted payload is 16 char iv + the actual encrypted payload
const encryptPayload = async (data: string, key: string): Promise<string> => {
  ...i validate data and key len etc here
  const iv = genIv();
  const base64 = await Aes.encrypt(data, toHex(key), toHex(iv), 'aes-128-cbc');
  return iv.concat(base64);
};
```

backend (in rust but hopefully it helps):  

```
/// Message must be base64 encoded string with iv at the start or the string.
pub fn decrypt(encrypted: &str, key: &str) -> Result<String, ServerError> {
    // Take everything after 16th char from the payload and base64 decode it
    let base64_decoded =
        base64::decode(&encrypted[16..]).map_err(|e| ServerError::DecryptError {
            message: e.to_string(),
        })?;

    // This is the iv as aes cipher, first 16 characters from the payload
    let cipher =
        Aes128Cbc::new_from_slices(key.as_ref(), encrypted[..16].as_ref()).map_err(|e| {
            ServerError::DecryptError {
                message: e.to_string(),
            }
        })?;

    // Decrypt base64 payload with the iv cipher to vector of u8
    let ciphertext =
        cipher
            .decrypt_vec(&base64_decoded)
            .map_err(|e| ServerError::DecryptError {
                message: e.to_string(),
            })?;

    // Parse the u8 vector to string
    String::from_utf8(ciphertext).map_err(|e| ServerError::DecryptError {
        message: e.to_string(),
    })
}
```
